export default {
  LABELS_DEFAULT_COLOR: "lightblue",
  LIGHT: "#FFF",
  DARK: "#000000",
  ERROR: "#985E6D",

  PRIMARY_BG: "#192231",
  PRIMARY_COLOR: "#FFFFFF",
  PRIMARY_LIGHT_BG: "#494E6B",
  PRIMARY_LIGHT_COLOR: "#FFFFFF",
  SECONDARY_BG: "#985E6D",
  SECONDARY_COLOR: "#FFFFFF",
  SECONDARY_LIGHT_BG: "#98878F",
  SECONDARY_LIGHT_COLOR: "#FFFFFF"
};
