export const FETCH_BOARDS = "FETCH_BOARDS";
export const SET_BOARDS = "SET_BOARDS";
export const RESET_BOARDS = "RESET_BOARDS";

export const FETCH_LABELS = "FETCH_LABELS";
export const SET_LABELS = "SET_LABELS";
export const RESET_LABELS = "RESET_LABELS";

export const SET_SELECTED_BOARD = "SET_SELECTED_BOARD";
export const RESET_SELECTED_BOARD = "RESET_SELECTED_BOARD";
export const SET_SELECTED_LABEL = "SET_SELECTED_LABEL";
export const RESET_SELECTED_LABEL = "RESET_SELECTED_LABEL";

export const FETCH_CARDS = "FETCH_CARDS";
export const SET_CARDS = "SET_CARDS";
export const RESET_CARDS = "RESET_CARDS";
