export default {
  PRIMARY_BG: "#1C2331",
  PRIMARY_COLOR: "#FFFFFF",
  SECONDARY_BG: "#3F729B",
  SECONDARY_COLOR: "#FFFFFF",
  SUCCESS_BG: "#007E33",
  SUCCESS_COLOR: "#FFFFFF",
  DANGER_BG: "#FF4444",
  DANGER_COLOR: "#FFFFFF",
  WARNING_BG: "#FF8800",
  WARNING_COLOR: "#FFFFFF",
  INFO_BG: "#0099CC",
  INFO_COLOR: "#FFFFFF",
  LIGHT: "#FFFFFF",
  DARK: "#212121"
};
